notmuch: really kill offlineimap when it hangs for too long

diff --git a/notmuch/hook-pre-new b/notmuch/hook-pre-new
--- a/notmuch/hook-pre-new
+++ b/notmuch/hook-pre-new
@@ -14,7 +14,7 @@ ret=0
 bakfile=$CONFIGDIR/bak/db-$(date +"%Y%m%d").xz
 if [ ! -e "$bakfile" ]; then
     echo "Starting backup..."
-    
+
     ((notmuch dump | xz > "$bakfile") || (echo "Backup failed." && ret=1)) &
 fi
 
@@ -26,7 +26,8 @@ for ((i=$MAXLOGS-1; i >= 0; i--)); do
 done
 
 echo "Fetching mail..."
-timeout 4m offlineimap -o > "$CONFIGDIR/log/mail.0.log" || (echo "Fetch mail failed." && ret=1)
+timeout -k 1m 4m offlineimap -o > "$CONFIGDIR/log/mail.0.log" || (echo "Fetch mail failed." && ret=1)
+find ~/.offlineimap -type f -name '*.lock' -delete
 
 wait
 
